### ISSUE TITLE
Spec checksums have changed

### ISSUE THREAD

**Issue by Benuuu** [CocoaPods/Specs#13033]
After running pod install, a lot of my project's spec checksums have changed.  Many of these are not from any sort of version change, so I would not expect the checksums to change.

I believe the offending commit is: https://github.com/CocoaPods/Specs/commit/d05c8cc2fd247198db1d6c56bcc25874fe66508d

**Comment by Keithbsmiley** [comment]
I don't believe that commit is the culprit. I believe 0.36.0 changed the way checksums work. Did you run `pod install` with this new version? Either way we're not going to undo that commit, so I'm closing this. Sorry for the unexpected result.

**Comment by Benuuu** [comment]
I'm still running 0.35.0, testing it against a person Specs repo changed the checksum.

**Comment by rwickliffe** [comment]
I'm running 0.36.0, have made no other changes since the last pod install and have the same issue. I'm also of the opinion that the commit referenced is indeed the culprit as AFNetworking 2.5.2 did **not** change and apparently was not included in the 32,114 files changed. It'd be nice to know if that truly is the case or if something else is going on here.
