### ISSUE TITLE
Request to delete Tealium... repos

### ISSUE THREAD

**Issue by jalakoo** [CocoaPods/Specs#13076]
Is it possible to delete the following specs:

Tealium_Full
Tealium_Compact
Tealium-Full

These passed the lint test but don't actually work at this time.  Would like to upload new repos later with proper camel case naming convention other specs are using.

**Comment by Keithbsmiley** [comment]
You can submit a pull request to remove the existing versions. This is strongly discouraged because if you do this it will break any user's projects which are using your specs. In theory you could add your new versions and mark the old ones as `deprecated_in_favor_of` the new ones. This would probably be preferred. Also, I haven't looked at these libraries but just based on their names it sounds like you could have a single spec with multiple subspecs to do what you want to.
