### ISSUE TITLE
ReactiveCocoa broken: metamacros.h not found with CocoaPods-Installation

### ISSUE THREAD

**Issue by itinance** [CocoaPods/Specs#13164]
When ReactiveCocoa was installed with CocoaPods, some required files are missed:

metamacros.h, imported in RACTuple.h
EXTScope.h, imported in NSNotificationCenter+RACSupport.h

I tried out different Versions: 2.1.8, 2.4.7, 2.5.0 with XCode 6.3.2.

Steps to reproduce:

create a new Project with XCode, Single View Application, called "RCFail"
add a Podfile to the directory with following content: pod 'ReactiveCocoa', '~> 2.4.7' (or any other version or now explicit version to get 2.5.0 right now)
open the RCFail.xcworkspace with XCode
build the project (or at least, try to build)
RCError/Pods/ReactiveCocoa/ReactiveCocoa/RACTuple.h:10:9: 'metamacros.h' file not found
RCError/Pods/ReactiveCocoa/ReactiveCocoa/NSNotificationCenter+RACSupport.m:10:9: fatal error: 'EXTScope.h' file not found
#import "EXTScope.h"

Is there any way to use ReactiveCocoa with CocoaPods right now?

$ xcodebuild -version
Xcode 6.3.2
Build version 6D2105

**Comment by squarefrog** [comment]
You should report this [upstream](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/new).

**Comment by itinance** [comment]
i was sent here by the guys at ReactiveCocoa
https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2070

**Comment by squarefrog** [comment]
Wait a minute. This feels familiar to what I experienced last week. Are you using `gnu-sed` ?

**Comment by itinance** [comment]
Actually i am just the consumer of cocoapods and the only thing i did was "pod install" :)
I am not familiar with pods-internals and so i'm unable to answer your question.

**Comment by squarefrog** [comment]
So I followed along with your steps using built in `sed`:

    $ sed --version
    sed: illegal option -- -
    usage: sed script [-Ealn] [-i extension] [file ...]
           sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

And I got no build errors at all. Using the `gnu-sed` installed through [Homebrew](https://brew.sh):

    $ brew install gnu-sed --with-default-names


    $ sed --version
    sed (GNU sed) 4.2.2
    Copyright (C) 2012 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Written by Jay Fenlason, Tom Lord, Ken Pizzini,
    and Paolo Bonzini.
    GNU sed home page: <http://www.gnu.org/software/sed/>.
    General help using GNU software: <http://www.gnu.org/gethelp/>.
    E-mail bug reports to: <bug-sed@gnu.org>.
    Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.

And I get the same errors you experienced. This is due to the [`prepare_command`](https://github.com/CocoaPods/Specs/blob/786e73d2142311b8947367725c93194d4306c2bd/Specs/ReactiveCocoa/2.5/ReactiveCocoa.podspec.json#L23) in the Podspec. This is not an issue with CocoaPods.

Look at https://github.com/CocoaPods/Specs/issues/12326 for more information. If this does not fix your issue, perhaps @ashfurrow may know better?

**Comment by tabuchid** [comment]
I just started seeing this too. Did anyone find out if its a version of sed or find that messes it up?
cc/ @squarefrog @ashfurrow

**Comment by ashfurrow** [comment]
The latest RC of ReactiveCocoa does not use the `prepare_command`: https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/3.0-RC.1/ReactiveCocoa.podspec.json

The last 2.x release was in April, and I've not heard of this coming up again: https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/2.5/ReactiveCocoa.podspec.json

@tabuchid could you please provide your CocoaPods version, OS X version, Xcode version, Podfile, and ruby config (if applicable)? We'll take a look.

**Comment by tabuchid** [comment]
Thanks for getting back @ashfurrow. This was happening to me on both Cocoapods 0.38.2 and 0.37.2.
Turns out something failed, I still am not sure what with the file renames in the prepare_command and the result got cached by Cocoapods. I think the core issue was a version of sed or find I had installed but even after resolving that I was still seeing the problem until I cleared the cocoapods cache.
The thing that made it hard to debug I think is that cocoapods doesn't log out if its using the cache or when its doing a prepare command even when you enable the verbose flag. At least as far as I could tell. Maybe I missed something in the docs.
