### ISSUE TITLE
CocoaPods 0.34 is now unsupported

### ISSUE THREAD

**Issue by hughlang** [CocoaPods/Specs#13170]
By changing the minimum required version to 0.35, all of our builds across a dozen apps are suddenly broken.  We have not been able to migrate to newer versions of Cocoapods and so this is a catastrophic problem. 

Please re-instate 0.34 compatibility. 

We would appreciate a warning before making changes like this.

**Comment by keith** [comment]
// @segiddins

**Comment by segiddins** [comment]
This was intentional, Kyle and I and Orta agreed it was time. 

-Samuel E. Giddins

On Jun 9, 2015, at 5:44 PM, Keith Smiley <notifications@github.com> wrote:

// @segiddins

**Comment by Drewsmits** [comment]
We have the same issue at my company. Due to licensing, we actually fork and host all 3rd party repos we depend on internally, and actually don't need the master repo at all. Instead we rely on our private instenal podspec repo.

It would be fantastic if there was a way to remove all dependencies on the master repo, and completely insulate our tools from changes like this.

**Comment by Drewsmits** [comment]
For those of you running the same fire drill I just had to, we ended up hacking the CocoaPods-version.yml by creating an alias for `pod install`. This unblocked our build machines as we look to upgrade cocoapods when time allows.

```
alias myPodInstall="sed -i -e 's/min: 0.35.0/min: 0.34.0/' ~/.cocoapods/repos/master/CocoaPods-version.yml; pod install"
```

**Comment by hughlang** [comment]
Thanks for that tip @Drewsmits

**Comment by y326760432** [comment]
please !!!!!

**Comment by y326760432** [comment]
@Drewsmits  how can i do ?

**Comment by TofPlay** [comment]
Same issue at my company too.

@segiddins you can not just change the minimum version without any warnings! :-1:

**Comment by qLag** [comment]
@segiddins :-1: 
Same issue at my company too. Really disappointed, that's not pro...

**Comment by CLIANG217** [comment]
@Drewsmits 
Thanks a lot. It works for me

**Comment by segiddins** [comment]
Hey, this was a team decision we made to help us get to cocoapods 1.0 faster. 0.35 is over six months old, and even it is unsupported at this point (again, see pre-1.0)

-Samuel E. Giddins

On Jun 10, 2015, at 6:59 AM, Chen LIANG <notifications@github.com> wrote:

@Drewsmits 
Thanks a lot. It works for me

**Comment by qLag** [comment]
I understand but you should clearly say that you will deprecate older versions than 35.0 to let us time to migrate more easily. 
Today, it means that all our framework releases does not work anymore because they need to use Cocoapods 0.33.1 . You are becoming the major dependency manager for Swift/Obj-C projects, and you surely have thousands users. A good communication about this kind of decision **essential** ...

Really disappointing ....

**Comment by floere** [comment]
@qLag Please refrain from personal attacks. We will ignore or delete comments that contain personal attacks. Your frustration is understandable, to a certain extent, but venting here will not help one bit.

**Comment by floere** [comment]
@qLag Singling out a single person is personal e.g. "that guy".

**Comment by qLag** [comment]
Okay sorry, edited. There is one name on a commit so ... 

But i always supported your project, i just want you understand what i try to explain (with my bad english). Anyway, the subject is now closed for me (i use @Drewsmits trick).

**Comment by floere** [comment]
@qLag No worries - I see. There will always be just a single team member on a commit - but we decide and execute as a team. In this case as well.

**Comment by Drewsmits** [comment]
@floere Thanks for the context. Is there a way to remove the public master repo as a dependency? I'd like to only use our private podspec repo, and insulate our toolset from changes like this.

**Comment by TofPlay** [comment]
@qLag :+1: 
>I understand but you should clearly say that you will deprecate older versions than 35.0 many days ago, to let us time to migrate more easily. 
Today, it means that all our framework releases does not work anymore because they need to use Cocoapods 0.33.1 . You are becoming the major dependency manager for Swift/Obj-C projects, and you surely have thousands users. A good communication about this kind of decision is essential (blog, newsletter... i don' know) ...
>Really disappointing ....
>EDIT : it's not a personal attack and i don't hate you, i suggest ideas to avoid this for the future.

**Comment by kylef** [comment]
### Why the minimum version has been bumped

This version has been bumped for a number of reasons, there have been many changes to the podspec DSL in CocoaPods 0.35 and onwards. Some of those changes have been backwards incompatible. For example in CocoaPods 0.35 the semantics behind `requires_arc` have been changed. There are many specifications in the specs repository that require newer CocoaPods versions.

This will actually no longer be required in the next coming release of CocoaPods because podspecs will be able to specify a version of CocoaPods they require. https://github.com/CocoaPods/Core/issues/240

We've given users over 8 months to migrate to CocoaPods 0.35, and we've offered many betas and release candidates of each release for users to test and give us feedback if it breaks a project. We're now 18 releases ahead of 0.35 and these issues haven't surfaced before, unfortunately we simply cannot know what we cannot know, even if we try really hard to do so.

Until CocoaPods 1.0.0 is out, it's essential to move users forward to the latest versions. Remember, [CocoaPods is not yet ready for prime-time](https://guides.cocoapods.org/using/faq.html#cocoapods-is-not-ready-for-prime-time-yet) and things are likely to break until we reach a stable 1.0.0. We are using semantic versioning.

We're using semantic versioning and until version 1.0.0 anything may change at any time and there is no API stability.

> 4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I agree, we should of communicated this better, we did not expect or realise so many users would be running older versions of CocoaPods. We communicate each update and `pod install` mentions that there is a new update available. In future we should certainly make this announcement and it will be happening less frequently in the future as we get closer and closer to CocoaPods 1.0.0.

We should make the message that `pod install` emits regarding newer versions more explicit that users should update to new versions sooner rather than later until we reach 1.0.0.

**Comment by kylef** [comment]
### How you can work around this problem

You can still use CocoaPods 0.33, you will just need to use an older version of the specs repo which is compatible with CocoaPods 0.33. This can be achieved by checking out an older commit and then using `pod install --no-repo-update`.

```bash
$ cd ~/.cocoapods/repos/master/
$ git checkout 4506d8bd
$ cd to my project
$ pod install --no-repo-update
```

#### Sources

> Due to licensing, we actually fork and host all 3rd party repos we depend on internally, and actually don't need the master repo at all. Instead we rely on our private instenal podspec repo.

In this case (@Drewsmits), if you specify your source repositories (as required in CocoaPods 0.34 and onwards). CocoaPods won't look at the version of the master spec repository.

```ruby
source 'https://github.com/Artsy/Specs'
```

**Comment by kylef** [comment]
> We were obliged to stay with version 0.33.1 because of some incompatibilities with new version of CocoaPods and existing projects

We weren’t aware of any outstanding or major bugs introduced in CocoaPods 0.35 and onwards preventing users from migrating. Can you please [report separate issues](https://github.com/CocoaPods/CocoaPods/issues/new) covering the problems you are facing in our issue tracker.

**Comment by hughlang** [comment]
Thanks @kylef.  I've learned much from your last few posts.

**Comment by Drewsmits** [comment]
@kylef Thanks for the detailed info! Currently we take advantage of the sources feature. However, I noticed that even if I removed the master spec repo as a source, it still attempted to download it. In fact, any pod command I ran, like `pod --help`, would attempt to sync the master repo first. For context, I'm on 0.34.1. 

And thanks for free software and the support! If you ever want to talk to someone that uses cocoapods in a massive org, please feel free to reach out.

**Comment by kylef** [comment]
I've reverted this change in f5f369a and now the master specs repository will work with CocoaPods 0.32.1 and onwards.

I'd highly encourage you to get on the latest version as soon as possible as we will be bumping the version back in the near future. We don't have a date when we will do this yet but we will update this thread once we've figured this out and a better strategy for doing this in the future.

**Comment by alloy** [comment]
> We can not build our projects on tool where they manage version like this. It's may be time to find another tool... 
> If you know other dependencies managers thank you to post them here.

@TofPlay Your comments are really not ok. Up to now @segiddins has been spending amazing amounts of time on creating something that you were using for free and now you are treating him as if it was his task to work for you and didn’t do his work right. The truth is that he does not owe you a single thing.

You’re also free to use other tools, but there’s no need to rally the crowd here, which serves only to attack @segiddins and I suspect you are doing that on purpose and I will not have it as he only deserves gratitude.

So please kindly stop using CocoaPods and leave it at that _or_ be helpful like the others on this thread have been and be part of the solution.

**Comment by hughlang** [comment]
Thanks everyone! It's great to have a small reprieve. 

I will work with my team to move us forward to the latest CocoaPods version.

**Comment by alloy** [comment]
> Currently we take advantage of the sources feature. However, I noticed that even if I removed the master spec repo as a source, it still attempted to download it. In fact, any pod command I ran, like pod --help, would attempt to sync the master repo first. For context, I'm on 0.34.1.

@Drewsmits Can you please file a ticket for that? Being able to completely not use the master repo is a desirable feature :+1:

**Comment by qLag** [comment]
@kylef @floere @segiddins  Okay thanks for details. I think everything is clear now for all of us :)

**Comment by azhabort** [comment]
@kylef thanks for supporting back old versions! :+1:
